## Notebook com exemplos de uso e análises

In [9]:
from getdatalol import GetDataLol
API_KEY = "RGAPI-4125cf79-8553-489b-bc7a-da7510b581df"
objget = GetDataLol(API_KEY, server="BR1", region="AMERICAS", output_path="D:/data/LOL")

Iniciando GetDataLol, para o servidor: BR1 e região: AMERICAS.

In [2]:
r1 = objget.get_data("https://{region}.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}?api_key={api_key}", gameName="iResi", tagLine="BR1")
print(r1)
r1 = objget.get_data("https://{region}.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}?api_key={api_key}", gameName="frosty", tagLine="KR3")
print(r1)

Requisititando dados de: https://AMERICAS.api.riotgames.com/riot/account/v1/accounts/by-riot-id/iResi/BR1?api_key=RGAPI-4125cf79-8553-489b-bc7a-da7510b581df
Dados requisitados com sucesso
{'puuid': 'smVq8PGKNLFVatly_fkSFLP_WLYlKULVsPGepMCWWqGMg3oq1ktg5fnporX3aKmiiFlZEApJEwY59w', 'gameName': 'iResi', 'tagLine': 'BR1'}
Requisititando dados de: https://AMERICAS.api.riotgames.com/riot/account/v1/accounts/by-riot-id/frosty/KR3?api_key=RGAPI-4125cf79-8553-489b-bc7a-da7510b581df
Dados requisitados com sucesso
{'puuid': 'V6LrFdRy53bp_HtS_tKE-S8Ete52saUNFLuhFr2G-B2hj4jvpwDcY9cfzV3gOQtP_XTkaSU-WsCdwA', 'gameName': 'frosty', 'tagLine': 'KR3'}

In [29]:
import pandas as pd
df_challenger_daily = pd.read_parquet(f"D:/data/LOL/tb_challenger_daily.parquet")
display(df_challenger_daily)

,summonerId,leaguePoints,rank,wins,losses,veteran,inactive,freshBlood,hotStreak,position,dat_ref_carga
0,ZmJFu-xTU7GiBQZFZ6-gs8H7hjmgpO_vqHnhYva2E1ceOk...,760,I,65,24,False,False,True,False,1,2024-10-03
1,UE5iWu-jaemV3ZWBJN3yCHJuQTILj07AatKxZm_Xd61pGA8,504,I,54,25,False,False,True,False,2,2024-10-03

In [35]:
import pandas as pd
df_summoners = pd.read_parquet(f"D:/data/LOL/tb_summoners.parquet")
display(df_summoners)

,accountId,puuid,profileIconId,revisionDate,summonerLevel,last_dat_ref_carga,id
0,c26m5K0Hgzdgo_i_A43hM1FMCXcQ-OQ9iI66FGIEn5vZ--8,V6LrFdRy53bp_HtS_tKE-S8Ete52saUNFLuhFr2G-B2hj4...,4856,1727904649000,993,2024-10-03,UE5iWu-jaemV3ZWBJN3yCHJuQTILj07AatKxZm_Xd61pGA8
1,ZmQqLBRoqixhupFsdkkLyazAALw5yz0q1UC21Js9lVe94R...,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,6498,1727993909153,146,2024-10-03,ZmJFu-xTU7GiBQZFZ6-gs8H7hjmgpO_vqHnhYva2E1ceOk...

In [34]:
import pandas as pd
df_summoners_hist = pd.read_parquet(f"D:/data/LOL/tb_summoners_hist.parquet")
display(df_summoners_hist)

,alter_data,dat_ref_carga,id
0,{'accountId': 'c26m5K0Hgzdgo_i_A43hM1FMCXcQ-OQ...,2024-10-03,UE5iWu-jaemV3ZWBJN3yCHJuQTILj07AatKxZm_Xd61pGA8
1,{'accountId': 'ZmQqLBRoqixhupFsdkkLyazAALw5yz0...,2024-10-03,ZmJFu-xTU7GiBQZFZ6-gs8H7hjmgpO_vqHnhYva2E1ceOk...

In [24]:
df_match_infos.groupby('matchId').count()

C:\Users\carlo\AppData\Local\Temp\ipykernel_13388\1345487900.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_match_infos.groupby('matchId').count()

,dataVersion,participants,allInPings,assistMePings,assists,baronKills,basicPings,bountyLevel,challenges,champExperience,...,gameId,gameMode,gameName,gameStartTimestamp,gameType,gameVersion,mapId,platformId,queueId,tournamentCode
matchId,,,,,,,,,,,,,,,,,,,,,
BR1_3005764981,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
BR1_3005797727,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
BR1_3005866630,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
BR1_3005876858,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
BR1_3005961069,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10

In [20]:
import pandas as pd
df_match_infos = pd.read_parquet(f"D:/data/LOL/tb_matchs_infos.parquet")
display(df_match_infos)

,dataVersion,participants,allInPings,assistMePings,assists,baronKills,basicPings,bountyLevel,challenges,champExperience,...,gameMode,gameName,gameStartTimestamp,gameType,gameVersion,mapId,platformId,queueId,tournamentCode,matchId
0,2,oAJ_fnNrPXJiyrX35i1HA1FxKZaHsJfsihFloew_aYM-gN...,0,0,6,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9686,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
1,2,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,0,5,7,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",8430,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
2,2,E2ZApw8VuNpLQKSMfrYguuzX4UhyczQAQrVqpgyT28nMQU...,2,2,4,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",10490,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
3,2,6ZKwC5uTmLej3XcZsLjDqSgz_lSrKyUmsekHbSSFhrpE3k...,0,4,2,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9435,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
4,2,CcMrL8xJPe-NRKOyei68mtTEyqCQ80QYrdIyY2Y5Hb9hmQ...,0,14,14,0,0,0,"{'12AssistStreakCount': 1, 'HealFromMapSources...",6565,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
5,2,Age_3iU9WvfXfgAzh_yxjFx0PAIU2azUSDtO23FpFv2xIp...,0,5,3,0,0,2,"{'12AssistStreakCount': 0, 'HealFromMapSources...",13647,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
6,2,Htuf2guMchMvfxDjyFR2HuVPQmadqDsJGmB0gekRCK7bih...,2,15,7,1,0,3,"{'12AssistStreakCount': 0, 'HealFromMapSources...",12645,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
7,2,Dsk_47rwX47kc4kSL6aPNMfZvWlRRQIDvvLxHOFEFWxCtP...,1,5,6,0,0,5,"{'12AssistStreakCount': 0, 'HealFromMapSources...",13661,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
8,2,c2xkj2Dtw994qLQksfW7YKkyQxb_95JAXa4QjSxAIXNH1S...,0,24,14,0,0,9,"{'12AssistStreakCount': 0, 'HealFromMapSources...",14635,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
9,2,dQoK_UFiD-CgDRMRhH9DldXasiZEVJFggbIZSlc4F5cNOa...,0,0,17,0,0,1,"{'12AssistStreakCount': 0, 'HealFromMapSources...",8519,...,CLASSIC,teambuilder-match-3005764981,1727925961607,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005764981
10,2,BvCdwTjyYwbesCnItNezhzd5tp86JHXhSPV-tuzUEAt8NE...,0,3,4,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",13317,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
11,2,fetaFU2FsfY14T0QOpZNG61f_5oP4zXI7KAM9SGJK0yuu_...,0,3,11,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",13076,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
12,2,A8SGClZW8z0q1FqBMS0bnZ-eIOOiNiBjEkOo2P3bel4HP0...,0,2,5,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",14999,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
13,2,iy-wDOv8TujTgiZij1recVBFvCQoL3j-_GOas8E0MpxKUz...,0,1,6,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",15402,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
14,2,kzFifLfS0562B6gGeu6Hr49ehRgRpDJYQo0m7LArJcB7Vg...,0,0,13,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",12013,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
15,2,eIL5MjnPxxB2Q8S8RpiSZKuOE6-tPABhYywmj2W_Nka6tM...,0,1,7,0,0,6,"{'12AssistStreakCount': 0, 'HealFromMapSources...",19926,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
16,2,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,1,5,14,1,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",17324,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
17,2,QyOSUPDAeTFA0KgPaleHX8cwF6cZICjSAeC-Z3vLEzK9yX...,1,9,11,1,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",17352,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
18,2,_dZUimdedJJtcflH87LLOK16OeKbkkiV_Y4oEp3hVtNKiA...,0,3,7,0,0,7,"{'12AssistStreakCount': 0, 'HealFromMapSources...",15536,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
19,2,VNfi77w0BqmMJ_fvdPoJDb8GXsQ16c6ZawMJAdpErvYCO7...,0,0,25,0,0,0,"{'12AssistStreakCount': 2, 'HealFromMapSources...",15427,...,CLASSIC,teambuilder-match-3005797727,1727935474610,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005797727
20,2,guFGNWWFEq1Nw6ZusXFdWcE6_V2EEHOZHJYd7Du7CMcNmD...,0,0,3,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9815,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
21,2,RSQTCChEhuz_34TRAwT-YYgJDQYjOYwlQ5SzuD4EfyVw0g...,0,2,15,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9205,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
22,2,nlrf1EQkW6iipJhLYnkk39-bciG5FNUz4fDvenGeFD6MZu...,0,3,2,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",11359,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
23,2,vtSUsiHPvnqRHcO4JuX-1IRYHooTtHGM7hCEQm74CcGRhV...,0,2,4,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",10142,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
24,2,SB0tkKuY12Q60vQrJo0DwKeXP96yYbgtjwB_-8c_LVkQxu...,0,0,15,0,0,4,"{'12AssistStreakCount': 0, 'HealFromMapSources...",7473,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
25,2,JZr1UA-QEjsfcAXT2hAy5YGdcy5PbdCshZtV4uQlN1UdGP...,0,2,2,0,0,3,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9244,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
26,2,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,0,0,4,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9077,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
27,2,t-XZM0H_s3QyvkoFrZJuevK2huEH7JLDvnBpr_-_MZrpfD...,0,3,3,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",10270,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
28,2,b-swescafsoYdaQ64Tda3V1mmzM1GeDUEfU0DXbFtntEjb...,1,4,2,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",10804,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
29,2,Ovjd3g6dLaGhyyKqhjvB_jk2hI-jqlMSFW9BgIUFfE-LMh...,0,5,7,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",6428,...,CLASSIC,teambuilder-match-3005866630,1727971622933,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005866630
30,2,eIL5MjnPxxB2Q8S8RpiSZKuOE6-tPABhYywmj2W_Nka6tM...,0,2,6,0,0,3,"{'12AssistStreakCount': 0, 'HealFromMapSources...",11441,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
31,2,lKamhusIZQrqYixyDAkLYyl065pQnMl-_eTHUWNblYOnx1...,0,6,15,0,0,3,"{'12AssistStreakCount': 0, 'HealFromMapSources...",10472,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
32,2,knhMp75e9LruYQeht5q0BkqsIvC7cdu2q2kk-hHbzqjheH...,0,3,8,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9969,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
33,2,Ms1g6Z7k5mt-PvPcS2rokNyujUXCL7huQPR9avKFI4FGLf...,0,7,15,0,0,13,"{'12AssistStreakCount': 0, 'HealFromMapSources...",11415,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
34,2,7ggrWLZBBQu_15Hu2U1E7XsVcIiBDIJm3MEUbeZnpDhPdu...,0,4,22,0,0,4,"{'12AssistStreakCount': 1, 'HealFromMapSources...",7392,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
35,2,-TetnsaKR9ItFbViLRIUqVbpO0nLKJZOEeImUNow5n3kCD...,0,3,2,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",8488,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
36,2,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,0,0,4,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",8543,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
37,2,vMXp0VE7Pccoy9kWFt87ODB3JTvdXixITF0ev-gyZbnzkE...,0,0,1,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",9572,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
38,2,mnQu46WOFjtCML-g5OxrzaQtEaZ1PMFAhx0SesaPs5eaOT...,0,1,2,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",7323,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
39,2,HeD6hor1Vnhh2P43565znu7KefVS5j2J6H_QFEiVkDHX3n...,0,2,5,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",5023,...,CLASSIC,teambuilder-match-3005876858,1727974280445,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005876858
40,2,6dOKV6PkRNe6f-WzzsbRe3QhIM0-emK3pbaOXe_ZK21scF...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
41,2,WGbosCicZhJWiKjP7aHKasZ0KsifYht6t-pT0sjdUQ6yC6...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
42,2,QO3VKjgBRjhupDi2IgU09xljd98PaaBZWjuYY7cqoLAgVb...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
43,2,loNeqaX6kZxU_JVtmo1ObkbC-ugaci4jQ6EEcswxVwvRlp...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
44,2,osM9wLh9yPD2kqzOjHRQqbSd7_obrDyGiRYLwC5WcNSi_f...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
45,2,bCpdXDv04z3huDqQb4fInC0Ppfb6-UxHlKoek-6X9iXtI1...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
46,2,9PVHOt0oEjbtjZV4mc7veo7Iq0VQpxyAlzctDjqHTF9ESf...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
47,2,jmpwQnJVqtK8Kzs9DJz1ZsC9wsNXRzREEl2IZXSUZ3pFfI...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
48,2,isQJItFjdRYj9WHormtbuISryO74rM4evt4H8a4tL3Jjrs...,0,1,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069
49,2,noNgrgrg1oEnRNwc2R5nbEK_uSsPhfOIds78BXKS7Prw9E...,0,0,0,0,0,0,"{'12AssistStreakCount': 0, 'HealFromMapSources...",0,...,CLASSIC,teambuilder-match-3005961069,1727990319988,MATCHED_GAME,14.19.622.3713,11,BR1,420,,BR1_3005961069

In [26]:
import pandas as pd
df_match_time = pd.read_parquet(f"D:/data/LOL/tb_matchs_timeline.parquet")
display(df_match_time)

,event,realTimestamp,timestamp,type,championStats,currentGold,damageStats,goldPerSecond,jungleMinionsKilled,level,...,gameMode,gameName,gameStartTimestamp,gameType,gameVersion,mapId,platformId,queueId,tournamentCode,matchId
0,NaN,NaN,NaN,None,None,NaN,None,NaN,NaN,NaN,...,CLASSIC,teambuilder-match-3005764981,1.727926e+12,MATCHED_GAME,14.19.622.3713,11.0,BR1,420.0,,BR1_3005764981
1,NaN,NaN,NaN,None,None,NaN,None,NaN,NaN,NaN,...,CLASSIC,teambuilder-match-3005764981,1.727926e+12,MATCHED_GAME,14.19.622.3713,11.0,BR1,420.0,,BR1_3005764981
2,NaN,NaN,NaN,None,None,NaN,None,NaN,NaN,NaN,...,CLASSIC,teambuilder-match-3005764981,1.727926e+12,MATCHED_GAME,14.19.622.3713,11.0,BR1,420.0,,BR1_3005764981
3,NaN,NaN,NaN,None,None,NaN,None,NaN,NaN,NaN,...,CLASSIC,teambuilder-match-3005764981,1.727926e+12,MATCHED_GAME,14.19.622.3713,11.0,BR1,420.0,,BR1_3005764981
4,NaN,NaN,NaN,None,None,NaN,None,NaN,NaN,NaN,...,CLASSIC,teambuilder-match-3005764981,1.727926e+12,MATCHED_GAME,14.19.622.3713,11.0,BR1,420.0,,BR1_3005764981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2.0,NaN,108013.0,None,"{'abilityHaste': 0.0, 'abilityPower': 0.0, 'ar...",0.0,"{'magicDamageDone': 0.0, 'magicDamageDoneToCha...",0.0,0.0,1.0,...,None,None,NaN,None,None,NaN,None,NaN,None,BR1_3005961069
102,2.0,NaN,108013.0,None,"{'abilityHaste': 0.0, 'abilityPower': 18.0, 'a...",50.0,"{'magicDamageDone': 318.0, 'magicDamageDoneToC...",0.0,0.0,1.0,...,None,None,NaN,None,None,NaN,None,NaN,None,BR1_3005961069
103,2.0,NaN,108013.0,None,"{'abilityHaste': 0.0, 'abilityPower': 27.0, 'a...",0.0,"{'magicDamageDone': 318.0, 'magicDamageDoneToC...",0.0,0.0,1.0,...,None,None,NaN,None,None,NaN,None,NaN,None,BR1_3005961069
104,2.0,NaN,108013.0,None,"{'abilityHaste': 0.0, 'abilityPower': 0.0, 'ar...",0.0,"{'magicDamageDone': 0.0, 'magicDamageDoneToCha...",0.0,0.0,1.0,...,None,None,NaN,None,None,NaN,None,NaN,None,BR1_3005961069
105,2.0,NaN,108013.0,None,"{'abilityHaste': 0.0, 'abilityPower': 9.0, 'ar...",0.0,"{'magicDamageDone': 0.0, 'magicDamageDoneToCha...",30.0,0.0,1.0,...,None,None,NaN,None,None,NaN,None,NaN,None,BR1_3005961069